
import { Category, Service } from './types';

export const COLORS = {
  primary: "#2F2003",
  accent: "#B08D57",
  cream: "#F9F8F6",
  border: "#E7E5E4",
  textBody: "#5C554B"
};

export const MOCK_SERVICES = [
  // --- LIVING: REAL ESTATE ---
  {
    id: 're-1',
    title: "Mansion at La Zagaleta",
    category: "real-state",
    location: "Benahavís",
    price: 12500000,
    unit: "venta",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Zagaleta Realty",
    status: "Approved",
    description: "An architectural masterpiece in Europe's most exclusive gated community. 8 bedrooms, private cinema, and views to Africa."
  },
  {
    id: 're-2',
    title: "Golden Mile Beachfront Penthouse",
    category: "real-state",
    location: "Marbella",
    price: 6400000,
    unit: "venta",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Golden Mile Estates",
    status: "Approved",
    description: "Duplex penthouse with direct sea views, private plunge pool, and 24/7 concierge service in the heart of the luxury strip."
  },
  {
    id: 're-3',
    title: "Sierra Blanca Modernist Villa",
    category: "real-state",
    location: "Sierra Blanca",
    price: 8900000,
    unit: "venta",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Luxury Homes Marbella",
    status: "Approved",
    description: "Sleek lines and state-of-the-art home automation in Marbella's most prestigious hillside neighborhood."
  },
  {
    id: 're-4',
    title: "Golf Valley Contemporary Mansion",
    category: "real-state",
    location: "Nueva Andalucía",
    price: 4200000,
    unit: "venta",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "Golf Valley Properties",
    status: "Approved",
    description: "Frontline golf estate with zero-edge pool and integrated spa, perfect for the passionate golfer and entertainer."
  },
  {
    id: 're-5',
    title: "Casco Antiguo Palace",
    category: "real-state",
    location: "Marbella Center",
    price: 2800000,
    unit: "venta",
    image: "https://images.unsplash.com/photo-1513584684374-8bdb7489feef?q=80&w=1200&auto=format&fit=crop",
    rating: 4.7,
    provider: "Historical Marbella Realty",
    status: "Approved",
    description: "A renovated 18th-century residence blending historic charm with modern luxury in the iconic Old Town."
  },

  // --- LIVING: PROPERTY MANAGEMENT ---
  {
    id: 'pm-1',
    title: "Elite Home Watch Service",
    category: "property-management",
    location: "Costa del Sol",
    price: 450,
    unit: "mes",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Marbella Care",
    status: "Approved",
    description: "Bi-weekly inspections, maintenance oversight, and security audits for your secondary residence."
  },
  {
    id: 'pm-2',
    title: "Holiday Rental Optimization",
    category: "property-management",
    location: "Marbella",
    price: 20,
    unit: "comisión %",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Yield Masters",
    status: "Approved",
    description: "Full guest management, dynamic pricing, and professional photography to maximize your rental income."
  },
  {
    id: 'pm-3',
    title: "Smart Home & Automation Care",
    category: "property-management",
    location: "Nueva Andalucía",
    price: 1200,
    unit: "año",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "TechHome Marbella",
    status: "Approved",
    description: "Specialized maintenance for Control4, Crestron, and high-end security systems. 24/7 technical support."
  },
  {
    id: 'pm-4',
    title: "Landscape & Pool Design Management",
    category: "property-management",
    location: "Sierra Blanca",
    price: 800,
    unit: "mes",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Marbella Green & Blue",
    status: "Approved",
    description: "Professional horticulture and chemical-free pool management for premium tropical gardens."
  },
  {
    id: 'pm-5',
    title: "Concierge Maintenance Support",
    category: "property-management",
    location: "Costa del Sol",
    price: 150,
    unit: "visita",
    image: "https://images.unsplash.com/photo-1621905252507-b35482cd84b4?q=80&w=1200&auto=format&fit=crop",
    rating: 4.7,
    provider: "Fix & Care Marbella",
    status: "Approved",
    description: "On-demand repairs, painting, and plumbing handled by multi-lingual professional contractors."
  },

  // --- LIVING: VILLA RENTAL ---
  {
    id: 'vr-1',
    title: "The White Palace Villa",
    category: "villa-rental",
    location: "Sierra Blanca",
    price: 35000,
    unit: "semana",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Platinum Villa Collection",
    status: "Approved",
    description: "Ultra-modern architecture with infinity pool, spa center, and staff on site. Pure opulence."
  },
  {
    id: 'vr-2',
    title: "Beachside Casita del Mar",
    category: "villa-rental",
    location: "Marbella East",
    price: 12000,
    unit: "semana",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "Sea & Sand Rentals",
    status: "Approved",
    description: "Charming beachfront villa with private garden, direct access to the dunes, and sunset views."
  },
  {
    id: 'vr-3',
    title: "Zen Retreat Estate",
    category: "villa-rental",
    location: "Benahavís",
    price: 22000,
    unit: "semana",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Marbella Zen Villas",
    status: "Approved",
    description: "Minimalist design focused on wellness. Features a yoga shala, organic garden, and saltwater pool."
  },
  {
    id: 'vr-4',
    title: "The Entertainer’s Villa",
    category: "villa-rental",
    location: "Nueva Andalucía",
    price: 18000,
    unit: "semana",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Marbella Club Properties",
    status: "Approved",
    description: "Equipped with a club-grade bar, DJ booth, game room, and heated outdoor cinema."
  },
  {
    id: 'vr-5',
    title: "Sierra Blanca Sky Estate",
    category: "villa-rental",
    location: "Sierra Blanca",
    price: 45000,
    unit: "semana",
    image: "https://images.unsplash.com/photo-1512918766775-d56aebb309f9?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Ultra Luxury Rentals",
    status: "Approved",
    description: "Highest point in Sierra Blanca. 10 bedrooms, heli-pad access, and 360 views of the Mediterranean."
  },

  // --- MOBILITY: CARS & CHAUFFEURS ---
  {
    id: 'cc-1',
    title: "Rolls Royce Phantom + Chauffeur",
    category: "cars-chauffeurs",
    location: "Puerto Banús",
    price: 1500,
    unit: "día",
    image: "https://images.unsplash.com/photo-1631214500115-598fc2cb882e?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Royal Transfers",
    status: "Approved",
    description: "The pinnacle of luxury transport. Professional multi-lingual chauffeur included for city tours or events."
  },
  {
    id: 'cc-2',
    title: "Lamborghini Huracán STO",
    category: "cars-chauffeurs",
    location: "Marbella",
    price: 2200,
    unit: "día",
    image: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Marbella Supercars",
    status: "Approved",
    description: "Self-drive experience for enthusiasts. Full insurance and delivery to your villa or hotel."
  },
  {
    id: 'cc-3',
    title: "VIP Armored SUV Security",
    category: "cars-chauffeurs",
    location: "Costa del Sol",
    price: 3500,
    unit: "día",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "SecurePath Marbella",
    status: "Approved",
    description: "Level B6 armored Range Rover with professional security driver for ultimate peace of mind."
  },
  {
    id: 'cc-4',
    title: "Classic Porsche 356 Rental",
    category: "cars-chauffeurs",
    location: "Marbella Center",
    price: 850,
    unit: "día",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop",
    rating: 4.7,
    provider: "Vintage Marbella",
    status: "Approved",
    description: "Iconic classic for photo shoots or elegant drives through the scenic white villages."
  },
  {
    id: 'cc-5',
    title: "Executive Mercedes V-Class",
    category: "cars-chauffeurs",
    location: "Málaga Airport",
    price: 450,
    unit: "transfer",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "VIP Shuttle Marbella",
    status: "Approved",
    description: "Luxury group transfer for up to 7 guests with WiFi, refreshments, and ample luggage space."
  },

  // --- MOBILITY: YACHTS ---
  {
    id: 'ya-1',
    title: "Sunseeker Predator 74",
    category: "yachts",
    location: "Puerto Banús",
    price: 5500,
    unit: "día",
    image: "https://images.unsplash.com/photo-1567899378494-47b22a2ec96a?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Banus yachts",
    status: "Approved",
    description: "Speed and style. Full crew, open bar, and premium catering included for a day in the Mediterranean."
  },
  {
    id: 'ya-2',
    title: "Princess 62 Flybridge",
    category: "yachts",
    location: "Estepona Marina",
    price: 3800,
    unit: "día",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Luxury Marine Estepona",
    status: "Approved",
    description: "Spacious flybridge perfect for families. Includes water toys: Seabobs, paddle boards, and jet ski."
  },
  {
    id: 'ya-3',
    title: "Classic Riva Aquarama",
    category: "yachts",
    location: "Marbella Club",
    price: 1200,
    unit: "4 horas",
    image: "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "Heritage Marine",
    status: "Approved",
    description: "The most beautiful boat ever built. Perfect for a romantic sunset cruise or high-end photography."
  },
  {
    id: 'ya-4',
    title: "Lagoon 52 Luxury Catamaran",
    category: "yachts",
    location: "Puerto Banús",
    price: 4500,
    unit: "día",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Catamaran Elite",
    status: "Approved",
    description: "Stable and vast. Ideal for larger groups or private events. Features multiple sun decks and bar."
  },
  {
    id: 'ya-5',
    title: "Mangusta 108 Superyacht",
    category: "yachts",
    location: "Puerto Banús",
    price: 18000,
    unit: "día",
    image: "https://images.unsplash.com/photo-1621275471769-e6aa344546d5?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Global Yacht Charters",
    status: "Approved",
    description: "The ultimate status symbol. 33 meters of pure luxury with a crew of 5. Full week charters available."
  },

  // --- MOBILITY: PRIVATE JETS & TRANSFERS ---
  {
    id: 'pj-1',
    title: "Citation Latitude Charter",
    category: "private-jets-transfers",
    location: "Málaga GAT",
    price: 14000,
    unit: "vuelo",
    image: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Marbella Aviation",
    status: "Approved",
    description: "Mid-size jet for up to 8 passengers. Direct flights to London, Paris, or Dubai with VIP catering."
  },
  {
    id: 'pj-2',
    title: "Helicopter Transfer: Marbella-Málaga",
    category: "private-jets-transfers",
    location: "Puerto Banús Heliport",
    price: 1800,
    unit: "vuelo",
    image: "https://images.unsplash.com/photo-1508197149814-0cc02e8b7f74?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "SkyPath Heli",
    status: "Approved",
    description: "Skip the traffic. 15-minute scenic transfer between Marbella and Málaga International Airport."
  },
  {
    id: 'pj-3',
    title: "Luxury Jet-to-Yacht Logistics",
    category: "private-jets-transfers",
    location: "Marbella",
    price: 2500,
    unit: "servicio",
    image: "https://images.unsplash.com/photo-1521316730702-829ad3878982?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Seamless Mobility",
    status: "Approved",
    description: "Coordinated transfer from your private flight directly to your yacht deck via helicopter or VIP tender."
  },
  {
    id: 'pj-4',
    title: "Phenom 300 Light Jet",
    category: "private-jets-transfers",
    location: "Costa del Sol",
    price: 8500,
    unit: "vuelo",
    image: "https://images.unsplash.com/photo-1464037862335-6c65a52bab89?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "Elite Flight",
    status: "Approved",
    description: "Agile and stylish light jet for European hops. Best-in-class cabin height and comfort."
  },
  {
    id: 'pj-5',
    title: "Executive Luggage & Valet Transfer",
    category: "private-jets-transfers",
    location: "Costa del Sol",
    price: 350,
    unit: "servicio",
    image: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?q=80&w=1200&auto=format&fit=crop",
    rating: 4.7,
    provider: "Marbella Valet",
    status: "Approved",
    description: "White-glove handling and transfer of excess luggage or high-value items from airport to residence."
  },

  // --- LIFESTYLE: DINING & NIGHTLIFE ---
  {
    id: 'dn-1',
    title: "Michelin Chef Private Experience",
    category: "dining-nightlife",
    location: "Villa Service",
    price: 250,
    unit: "persona",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Haute Cuisine Marbella",
    status: "Approved",
    description: "A 12-course tasting menu prepared in your villa by a starred chef. Includes wine pairing."
  },
  {
    id: 'dn-2',
    title: "Olivia Valere VIP Table",
    category: "dining-nightlife",
    location: "Marbella Club",
    price: 2000,
    unit: "mínimo",
    image: "https://images.unsplash.com/photo-1514525253344-a812ef9ee586?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "Nightlife Concierge",
    status: "Approved",
    description: "Prime seating at Marbella's most iconic club. Priority entry and dedicated host service."
  },
  {
    id: 'dn-3',
    title: "Authentic Tapas Wine Tour",
    category: "dining-nightlife",
    location: "Marbella Center",
    price: 180,
    unit: "persona",
    image: "https://images.unsplash.com/photo-1534080564583-6be75777b70a?q=80&w=1200&auto=format&fit=crop",
    rating: 4.7,
    provider: "Marbella Gourmet",
    status: "Approved",
    description: "Guided tour through the best hidden taverns of the Old Town. Premium wines and local delicacies."
  },
  {
    id: 'dn-4',
    title: "Beach Club Frontline Bed",
    category: "dining-nightlife",
    location: "Nikki Beach",
    price: 800,
    unit: "día",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Sun & Champagne",
    status: "Approved",
    description: "The best spot on the sand. Includes bottle of premium champagne and fruit platter."
  },
  {
    id: 'dn-5',
    title: "Rare Vintage Wine Tasting",
    category: "dining-nightlife",
    location: "Golden Mile",
    price: 500,
    unit: "persona",
    image: "https://images.unsplash.com/photo-1510850431481-7a23201f913f?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "The Marbella Sommelier",
    status: "Approved",
    description: "Private session featuring rare Spanish and French vintages. Expert commentary by master sommelier."
  },

  // --- LIFESTYLE: GOLF EXPERIENCES ---
  {
    id: 'ge-1',
    title: "Aloha Golf Club Day Member",
    category: "golf-experiences",
    location: "Nueva Andalucía",
    price: 250,
    unit: "green fee",
    image: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Marbella Golf Tours",
    status: "Approved",
    description: "Exclusive access to one of Marbella's most prestigious private courses. Buggy included."
  },
  {
    id: 'ge-2',
    title: "PGA Pro Coaching Session",
    category: "golf-experiences",
    location: "Los Naranjos",
    price: 120,
    unit: "hora",
    image: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Golf Academy Marbella",
    status: "Approved",
    description: "Improve your game with a former PGA tour professional. Video analysis and swing feedback."
  },
  {
    id: 'ge-3',
    title: "Finca Cortesin VIP Day",
    category: "golf-experiences",
    location: "Casares",
    price: 450,
    unit: "persona",
    image: "https://images.unsplash.com/photo-1610448721566-47369c768e70?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Ultimate Golf",
    status: "Approved",
    description: "The World’s best golf resort experience. Green fee, valet, luxury brunch, and spa access."
  },
  {
    id: 'ge-4',
    title: "Night Golf at La Dama",
    category: "golf-experiences",
    location: "Nueva Andalucía",
    price: 90,
    unit: "9 hoyos",
    image: "https://images.unsplash.com/photo-1592919016381-99617d9b98e7?q=80&w=1200&auto=format&fit=crop",
    rating: 4.6,
    provider: "Dama de Noche Golf",
    status: "Approved",
    description: "Unique illuminated course experience. Play under the stars on a fully lit professional course."
  },
  {
    id: 'ge-5',
    title: "Junior Elite Golf Camp",
    category: "golf-experiences",
    location: "Marbella",
    price: 1500,
    unit: "semana",
    image: "https://images.unsplash.com/photo-1526671304602-3a74ac105820?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "Rising Stars Golf",
    status: "Approved",
    description: "Professional training for young talents. Focus on technique, strategy, and mental game."
  },

  // --- SERVICES: DOMESTIC STAFF ---
  {
    id: 'ds-1',
    title: "Live-in Professional Butler",
    category: "domestic-staff",
    location: "Marbella",
    price: 4500,
    unit: "mes",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6958?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "British Butler Guild",
    status: "Approved",
    description: "Traditional service excellence. Wardrobe management, fine dining service, and estate organization."
  },
  {
    id: 'ds-2',
    title: "Professional Nanny (Maternity)",
    category: "domestic-staff",
    location: "Costa del Sol",
    price: 800,
    unit: "semana",
    image: "https://images.unsplash.com/photo-1544126592-807daa2e5cd8?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Marbella Nannies",
    status: "Approved",
    description: "Highly trained pediatric specialists for newborn care. Multi-lingual and background checked."
  },
  {
    id: 'ds-3',
    title: "Luxury Personal Shopper",
    category: "domestic-staff",
    location: "Puerto Banús",
    price: 100,
    unit: "hora",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1200&auto=format&fit=crop",
    rating: 4.7,
    provider: "Style Marbella",
    status: "Approved",
    description: "Access to private showrooms and new collections before they hit the boutiques. Style consultation."
  },
  {
    id: 'ds-4',
    title: "Deep Cleaning & Maid Team",
    category: "domestic-staff",
    location: "Marbella",
    price: 350,
    unit: "día",
    image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "Sparkle & Shine",
    status: "Approved",
    description: "Elite hospitality-standard cleaning for high-end properties. Team of 3 professionals."
  },
  {
    id: 'ds-5',
    title: "Private Bodyguard / Security",
    category: "domestic-staff",
    location: "Marbella",
    price: 650,
    unit: "turno",
    image: "https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Marbella Security Solutions",
    status: "Approved",
    description: "Discrete personal protection. Former special forces personnel with full licensing and expertise."
  },

  // --- SERVICES: MEDICAL CARE ---
  {
    id: 'mc-1',
    title: "24/7 Private Concierge Physician",
    category: "medical-care",
    location: "Costa del Sol",
    price: 2500,
    unit: "mes",
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Marbella Medical Group",
    status: "Approved",
    description: "Unlimited house calls and telemedicine. Fast-track access to top specialists and private hospitals."
  },
  {
    id: 'mc-2',
    title: "Wellness & IV Drip Therapy",
    category: "medical-care",
    location: "Villa Service",
    price: 280,
    unit: "sesión",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Revitalize Marbella",
    status: "Approved",
    description: "Vitamin and hydration infusions tailored to recovery, energy, or anti-aging. In-villa service."
  },
  {
    id: 'mc-3',
    title: "Premium Cosmetic Consultation",
    category: "medical-care",
    location: "Golden Mile",
    price: 150,
    unit: "consulta",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=1200&auto=format&fit=crop",
    rating: 4.8,
    provider: "Marbella Aesthetic Clinic",
    status: "Approved",
    description: "Consult with Europe's leading plastic surgeons. Advanced skin analysis and treatment planning."
  },
  {
    id: 'mc-4',
    title: "Physiotherapy & Osteopathy",
    category: "medical-care",
    location: "Marbella",
    price: 120,
    unit: "sesión",
    image: "https://images.unsplash.com/photo-1574607383476-f517f220d398?q=80&w=1200&auto=format&fit=crop",
    rating: 4.9,
    provider: "Body Balance Marbella",
    status: "Approved",
    description: "Sports injury recovery and holistic body alignment using the latest therapy techniques."
  },
  {
    id: 'mc-5',
    title: "Luxury Mental Health Coaching",
    category: "medical-care",
    location: "Costa del Sol",
    price: 200,
    unit: "sesión",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1200&auto=format&fit=crop",
    rating: 5.0,
    provider: "Marbella Mindset",
    status: "Approved",
    description: "High-performance coaching for executives and elite individuals. Focused on stress and life balance."
  }
];


export const categories = [
  {
    name: 'All',
    slug: 'all',
  },
  {
    name: 'Real Estate',
    slug: 'real-estate',
  },
  {
    name: 'Property Management',
    slug: 'property-management',
  },
  {
    name: 'Villa Rental',
    slug: 'villa-rental',
  },
  {
    name: 'Cars & Chauffeurs',
    slug: 'cars-chauffeurs',
  },
  {
    name: 'Yachts',
    slug: 'yachts',
  },
  {
    name: 'Private Jets & Transfers',
    slug: 'private-jets-transfers',
  },
  {
    name: 'Dining & Nightlife',
    slug: 'dining-nightlife',
  },
  {
    name: 'Golf Experiences',
    slug: 'golf-experiences',
  },
  {
    name: 'Domestic Staff',
    slug: 'domestic-staff',
  },
  {
    name: 'Medical Care',
    slug: 'medical-care',
  },
];
