import { type Metadata } from 'next'
import {
  ClerkProvider
} from '@clerk/nextjs'
import { Geist, Geist_Mono, Manrope, Playfair_Display } from 'next/font/google'
import './globals.css'

import MuiProvider from '@/providers/MuiProvider'
import QueryProvider from '@/providers/QueryProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
})

const playfairDisplay = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="light">
        <body className={`${playfairDisplay.variable} ${manrope.variable} antialiased`}>
          <QueryProvider>
            <MuiProvider>
              {children}
            </MuiProvider>
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}